import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import os

print(f"TensorFlow Version: {tf.__version__}")

# We will export the C-arrays to this file
OUTPUT_HEADER = "../firmware-teensy/src/models/dual_models.h"

def build_phonetic_model(window_length=50):
    """ Model A: 1D-CNN with dilated causal convolutions for Phonetic Regression """
    inputs = tf.keras.Input(shape=(window_length, 3)) # 3 Channels: sEMG L, sEMG R, PZT
    
    # Causal convolutions prevent looking into the "future", critical for real-time
    x = layers.Conv1D(16, kernel_size=3, padding="causal", activation="relu", dilation_rate=1)(inputs)
    x = layers.Conv1D(32, kernel_size=3, padding="causal", activation="relu", dilation_rate=2)(x)
    x = layers.Conv1D(32, kernel_size=3, padding="causal", activation="relu", dilation_rate=4)(x)
    
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dense(32, activation="relu")(x)
    
    # Output: 6-DOF (Pitch, Yaw, Intensity, F1, F2, F3)
    outputs = layers.Dense(6, activation="linear")(x)
    
    model = models.Model(inputs, outputs, name="Phonetic_1DCNN")
    model.compile(optimizer='adam', loss='mse')
    return model

def build_affective_model(long_window=100):
    """ Model B: Lightweight Dense/Shallow-CNN for Affective State """
    inputs = tf.keras.Input(shape=(long_window, 2)) # 2 Channels: EDA, f0 contour
    
    x = layers.Conv1D(8, kernel_size=5, strides=2, padding="valid", activation="relu")(inputs)
    x = layers.GlobalAveragePooling1D()(x)
    
    x = layers.Dense(16, activation="relu")(x)
    
    # Output: 2-DOF (Arousal, Valence)
    outputs = layers.Dense(2, activation="tanh")(x) # Tanh bounds output between -1.0 and 1.0
    
    model = models.Model(inputs, outputs, name="Affective_CNN")
    model.compile(optimizer='adam', loss='mse')
    return model

def evaluate_formant_accuracy(model, x_test, y_test):
    """
    Validation Metrics Module:
    Calculates the Mean Absolute Error (MAE) specifically for F1 and F2 in Hertz.
    Goal: MAE < 50Hz to claim high-fidelity phonetic synthesis.
    """
    print("\n[!] Running Formant Accuracy Validation...")
    predictions = model.predict(x_test, verbose=0)
    
    # Assuming y_test and predictions have F1 at index 3 and F2 at index 4 (from 6-DOF: Pitch, Yaw, Int, F1, F2, F3)
    f1_true = y_test[:, 3]
    f2_true = y_test[:, 4]
    
    f1_pred = predictions[:, 3]
    f2_pred = predictions[:, 4]
    
    mae_f1 = np.mean(np.abs(f1_true - f1_pred))
    mae_f2 = np.mean(np.abs(f2_true - f2_pred))
    
    print(f"    -> F1 Mean Absolute Error: {mae_f1:.2f} Hz")
    print(f"    -> F2 Mean Absolute Error: {mae_f2:.2f} Hz")
    
    if mae_f1 < 50.0 and mae_f2 < 50.0:
        print("    [SUCCESS] Formant MAE is under 50Hz. High-fidelity synthesis validated!")
    else:
        print("    [WARNING] Formant MAE exceeds 50Hz. Further training required.")

def convert_to_tflite_float32(model):
    """ Compiles to FLOAT32 TFLite to leverage the Cortex-M7 FPU natively """
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    # Default optimization without integer quantization leaves it at Float32
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float32]
    tflite_model = converter.convert()
    return tflite_model

def to_c_array(tflite_model, array_name):
    """ Equivalent to `xxd -i`. Converts raw bytes to C header array format """
    hex_array = [hex(b) for b in tflite_model]
    c_str = f"alignas(16) const unsigned char {array_name}[] = {{\n"
    
    for i in range(0, len(hex_array), 12):
        c_str += "  " + ", ".join(hex_array[i:i+12]) + ",\n"
        
    c_str += "};\n"
    c_str += f"const unsigned int {array_name}_len = {len(tflite_model)};\n"
    return c_str

def main():
    print("[+] Building Dual Architectures...")
    phonetic_model = build_phonetic_model()
    affective_model = build_affective_model()
    
    print("[+] Architecture summaries:")
    phonetic_model.summary()
    affective_model.summary()
    
    # Here is where the agent would load the dataset and call model.fit()
    # For now, we compile untrained structures to verify the pipeline.
    print("[!] Bypassing training - compiling structural flatbuffers...")
    
    # Mocking evaluation
    mock_x_test = np.random.rand(10, 50, 3)
    mock_y_test = np.random.rand(10, 6) * 1000 # Scale to hz range mock
    evaluate_formant_accuracy(phonetic_model, mock_x_test, mock_y_test)
    
    tflite_phonetic = convert_to_tflite_float32(phonetic_model)
    tflite_affective = convert_to_tflite_float32(affective_model)
    
    print("[+] Generating C-Byte Arrays...")
    phonetic_c = to_c_array(tflite_phonetic, "phonetic_model_tflite")
    affective_c = to_c_array(tflite_affective, "affective_model_tflite")
    
    header_content = f"""#ifndef DUAL_MODELS_H
#define DUAL_MODELS_H

// Auto-generated by CADENCE Model Training Pipeline (FLOAT32 TFLite)

{phonetic_c}

{affective_c}
#endif
"""
    
    with open(OUTPUT_HEADER, "w") as f:
        f.write(header_content)
        
    print(f"[SUCCESS] Wrote Dual Models to {OUTPUT_HEADER}")

if __name__ == "__main__":
    main()
